version: '3'
services:
  nginx:
    image: nginx:1.15-alpine
    depends_on:
      - backend
    ports:
      - "80:80"
    volumes:
      - ./nginx:/etc/nginx/conf.d
  backend:
    build: ./backend
    environment:
      - GIN_MODE=release
